/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopsproject;

import com.sun.jdi.connect.spi.Connection;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Siloo
 */
public class loginpage extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    

    public loginpage(JButton btnlogin, JLabel jLabel1, JLabel jLabel2, JTextField txtemail, JPasswordField txtpassword) throws HeadlessException {
        this.btnlogin = btnlogin;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.txtemailadmin = txtemail;
        this.txtpassword = txtpassword;
    }

    /**
     * Creates new form JFrame1
     */
    public loginpage() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemailadmin = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpasswordadmin = new javax.swing.JPasswordField();
        btnloginadmin = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        chkteacherpass = new javax.swing.JCheckBox();
        chkadminpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOGIN PAGE");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Email");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Password");

        txtemailadmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Email");

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setText("Password");

        txtpasswordadmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnloginadmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnloginadmin.setText("LOGIN");
        btnloginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginadminActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("TEACHER'S LOGIN SYSTEM");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setText("ADMIN LOGIN SYSTEM");

        chkteacherpass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkteacherpass.setText("check password");
        chkteacherpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkteacherpassActionPerformed(evt);
            }
        });

        chkadminpass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkadminpass.setText("check password");
        chkadminpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkadminpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnloginadmin)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemailadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkteacherpass)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpasswordadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkadminpass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtemailadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtpasswordadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkteacherpass)
                    .addComponent(chkadminpass))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloginadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
       String  email = txtemail.getText();
      String password = txtpassword.getText();
 
      String query =  "select  Teacher_id ,Teacher_Password, Teacher_Name, Teacher_Email, Course from teacher  where Teacher_Email = \"" +  email +"\"";
      Database db = new Database();
      ResultSet resultSet = db.fatchData(query);
 
         try {
             boolean LoginSuccess = false;
             int teacherId = -1;
         while (resultSet.next()) {
            teacherId = resultSet.getInt("Teacher_id");
            String dbEmail= resultSet.getString("Teacher_Email");
           String dbPassword= resultSet.getString("Teacher_Password");
            String name = resultSet.getString("Teacher_Name");
             String Course = resultSet.getString("Course");
        
                  
              
              if(password.equals(dbPassword) && email.equals(dbEmail)){
                  LoginSuccess = true;
                  JOptionPane.showMessageDialog(loginpage.this, "Login successfully");
                  new teacherForm(teacherId).setVisible(true);
                  this.setVisible(false);
                  
                
              } 
              
         }
              if(!LoginSuccess){
                  JOptionPane.showMessageDialog(loginpage.this, "Error! please fill correct information");
              }
         }  catch (Exception ex) {
                System.out.println(ex);
} finally {
             try{
                  if (resultSet != null) {
                resultSet.close();

                  }
               //   conn.close();
                  
             }catch (Exception e) {
              e.printStackTrace();
        }
         }
               
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnloginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginadminActionPerformed
        // TODO add your handling code here:
        String adminEmail = txtemailadmin.getText();
        String adminpassword = txtpasswordadmin.getText();
        String query =  "select  Admin_Id ,Admin_Password, Admin_Name, Admin_Email from admin  where Admin_Email = \"" +  adminEmail +"\"";
        Database db = new Database();
      ResultSet resultSet = db.fatchData(query);
      try {
          boolean LoginSuccessfull = false;
         while (resultSet.next()) {
            int ID = resultSet.getInt("Admin_Id");
            String dbEmail= resultSet.getString("Admin_Email");
           String dbPassword= resultSet.getString("Admin_Password");
            String name = resultSet.getString("Admin_Name");
       
             
             if(adminpassword.equals(dbPassword) && adminEmail.equals(dbEmail)){
                 LoginSuccessfull = true;
                  JOptionPane.showMessageDialog(loginpage.this, "Login successfully");
                  new adminForm().setVisible(true);
                  break;
              }
         }
         if(!LoginSuccessfull){
                  JOptionPane.showMessageDialog(loginpage.this, "Error! please fill correct information");
              }
             
         }  catch (Exception ex) {
                System.out.println(ex);
}   finally{
          try{
               if (resultSet != null) {
                resultSet.close();
            }
               conn.close();
          }catch (Exception e) {
            System.out.println(e);
        }
      }
          
    }//GEN-LAST:event_btnloginadminActionPerformed

    private void chkteacherpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkteacherpassActionPerformed
        // TODO add your handling code here:
        if(chkteacherpass.isSelected()){
        txtpassword.setEchoChar((char)0);
    }
        else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkteacherpassActionPerformed

    private void chkadminpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkadminpassActionPerformed
        // TODO add your handling code here:
        if(chkadminpass.isSelected()){
            txtpasswordadmin.setEchoChar((char)0);
            
        }
        else{
            txtpasswordadmin.setEchoChar('*');
        }
    }//GEN-LAST:event_chkadminpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnloginadmin;
    private javax.swing.JCheckBox chkadminpass;
    private javax.swing.JCheckBox chkteacherpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemailadmin;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JPasswordField txtpasswordadmin;
    // End of variables declaration//GEN-END:variables

    private static class PreparedStatement {

        public PreparedStatement() {
        }
    }
}
